import type { Subject } from '../../domain/catalog/subject';
export const subjectsMock: Subject[] = [
  {
    id: '1',
    code: 'INF-101',
    name: 'Introducción a la Programacion',
    careerName: 'Ingenieria Civil Informatica',
    semester: 1,
    professorName: 'Marcela Huenchul',
    notesCount: 34,
  },
  {
    id: '2',
    code: 'INF-204',
    name: 'Estructuras de Datos',
    careerName: 'Ingenieria Civil Informatica',
    semester: 3,
    professorName: 'Rodrigo Paillao',
    notesCount: 51,
  },
  {
    id: '3',
    code: 'INF-305',
    name: 'Bases de Datos',
    careerName: 'Ingenieria Civil Informatica',
    semester: 5,
    professorName: 'Camila Nanculef',
    notesCount: 28,
  },
  {
    id: '4',
    code: 'INF-402',
    name: 'Sistemas Operativos',
    careerName: 'Ingenieria Civil Informatica',
    semester: 6,
    professorName: 'Tomas Epulef',
    notesCount: 19,
  },
  {
    id: '5',
    code: 'IND-108',
    name: 'Algebra Lineal',
    careerName: 'Ingenieria Civil Industrial',
    semester: 2,
    professorName: 'Valentina Curiqueo',
    notesCount: 42,
  },
  {
    id: '6',
    code: 'IND-207',
    name: 'Investigacion de Operaciones',
    careerName: 'Ingenieria Civil Industrial',
    semester: 4,
    professorName: 'Felipe Mariman',
    notesCount: 15,
  },
  {
    id: '7',
    code: 'IND-310',
    name: 'Gestión de Procesos',
    careerName: 'Ingenieria Civil Industrial',
    semester: 6,
    professorName: 'Daniela Colipi',
    notesCount: 22,
  },
  {
    id: '8',
    code: 'PED-115',
    name: 'Didactica de las Matematicas',
    careerName: 'Pedagogia en Educacion Basica',
    semester: 3,
    professorName: 'Ignacia Millalonco',
    notesCount: 37,
  },
  {
    id: '9',
    code: 'PED-220',
    name: 'Psicologia del Aprendizaje',
    careerName: 'Pedagogia en Educacion Basica',
    semester: 4,
    professorName: 'Bastian Quintrileo',
    notesCount: 26,
  },
  {
    id: '10',
    code: 'ENF-130',
    name: 'Anatomia y Fisiologia',
    careerName: 'Enfermeria',
    semester: 2,
    professorName: 'Paula Necul',
    notesCount: 45,
  },
  {
    id: '11',
    code: 'ENF-240',
    name: 'Farmacologia General',
    careerName: 'Enfermeria',
    semester: 4,
    professorName: 'Cristobal Antinao',
    notesCount: 12,
  },
];